//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.3
//  DateTime: 2025/02/05 16:03:50
//  GPLEX input file <Parser\Parser.Language.analyzer.lex - 2025/02/05 16:03:17>
//  GPLEX frame file <embedded resource>
//
//  Option settings: verbose, parser, stack, minimize
//  Option settings: compressNext, persistBuffer, noEmbedBuffers
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;

namespace QuickCalc.Parser.Parser
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class ParserScanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class ParserScanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 52;
        const int initial = 53;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[] nxt;
        public Table(int m, int x, int d, sbyte[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {53, 0};

    static Table[] NxS = new Table[125] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ new Table(0, 0, -1, null), // Shortest string "\x01"
/* NxS[   2] */ // Shortest string "\t"
      new Table(9, 24, -1, new sbyte[] {2, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, 2}),
/* NxS[   3] */ new Table(0, 0, -1, null), // Shortest string "!"
/* NxS[   4] */ // Shortest string "#"
      new Table(48, 75, -1, new sbyte[] {52, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, -1, -1, -1, -1, -1, -1, -1, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52, -1, -1, -1, -1, 52, -1, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52}),
/* NxS[   5] */ new Table(0, 0, -1, null), // Shortest string "%"
/* NxS[   6] */ new Table(0, 0, -1, null), // Shortest string "&"
/* NxS[   7] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[   8] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[   9] */ // Shortest string "*"
      new Table(42, 1, -1, new sbyte[] {33}),
/* NxS[  10] */ new Table(0, 0, -1, null), // Shortest string "+"
/* NxS[  11] */ // Shortest string ","
      new Table(44, 79, -1, new sbyte[] {11, -1, 120, -1, 11, 11, 
          11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, 43, -1, 44, -1, -1, -1, 44, -1, 44, -1, -1, 44, 45, 
          45, -1, 44, -1, -1, -1, -1, 44, 44, -1, -1, -1, -1, -1, -1, 45, 
          -1, 45, 46, 123, 45, -1, 45, -1, -1, 45, -1, 45, 45, -1, 45, 45, 
          45, -1, -1, 45, -1, -1, -1, 45, 45}),
/* NxS[  12] */ new Table(0, 0, -1, null), // Shortest string "-"
/* NxS[  13] */ // Shortest string "/"
      new Table(47, 1, -1, new sbyte[] {51}),
/* NxS[  14] */ // Shortest string "0"
      new Table(44, 79, -1, new sbyte[] {11, -1, 120, -1, 11, 11, 
          11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, -1, -1, -1, -1, 
          121, -1, -1, 43, -1, 44, -1, -1, -1, 44, -1, 44, -1, -1, 44, 45, 
          45, -1, 44, -1, -1, -1, 122, 44, 44, -1, -1, -1, -1, -1, -1, 45, 
          121, 45, 46, 123, 45, -1, 45, -1, -1, 45, -1, 45, 45, -1, 45, 45, 
          45, -1, -1, 45, -1, -1, 122, 45, 45}),
/* NxS[  15] */ // Shortest string ":"
      new Table(65, 52, -1, new sbyte[] {106, -1, 107, -1, 108, -1, 
          -1, -1, 109, -1, -1, 110, -1, -1, -1, -1, -1, -1, 111, 112, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 106, -1, 107, -1, 108, -1, 
          -1, -1, 109, -1, -1, 110, -1, -1, -1, -1, -1, -1, 111, 112}),
/* NxS[  16] */ new Table(0, 0, -1, null), // Shortest string ";"
/* NxS[  17] */ // Shortest string "<"
      new Table(60, 1, -1, new sbyte[] {41}),
/* NxS[  18] */ new Table(0, 0, -1, null), // Shortest string "="
/* NxS[  19] */ // Shortest string ">"
      new Table(62, 1, -1, new sbyte[] {40}),
/* NxS[  20] */ // Shortest string "A"
      new Table(66, 45, -1, new sbyte[] {64, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 65, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 64, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 66}),
/* NxS[  21] */ // Shortest string "C"
      new Table(79, 33, -1, new sbyte[] {64, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 64}),
/* NxS[  22] */ // Shortest string "E"
      new Table(88, 33, -1, new sbyte[] {63, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 63}),
/* NxS[  23] */ // Shortest string "I"
      new Table(78, 33, -1, new sbyte[] {62, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62}),
/* NxS[  24] */ // Shortest string "L"
      new Table(78, 34, -1, new sbyte[] {38, 61, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38, 61}),
/* NxS[  25] */ // Shortest string "M"
      new Table(79, 33, -1, new sbyte[] {60, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 60}),
/* NxS[  26] */ // Shortest string "N"
      new Table(79, 33, -1, new sbyte[] {59, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 59}),
/* NxS[  27] */ // Shortest string "O"
      new Table(82, 33, -1, new sbyte[] {35, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 35}),
/* NxS[  28] */ // Shortest string "P"
      new Table(73, 33, -1, new sbyte[] {39, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 39}),
/* NxS[  29] */ // Shortest string "S"
      new Table(73, 41, -1, new sbyte[] {56, -1, -1, -1, -1, -1, 
          -1, -1, 57, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 56, -1, -1, -1, -1, -1, 
          -1, -1, 57}),
/* NxS[  30] */ // Shortest string "T"
      new Table(65, 33, -1, new sbyte[] {56, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 56}),
/* NxS[  31] */ // Shortest string "X"
      new Table(79, 33, -1, new sbyte[] {55, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 55}),
/* NxS[  32] */ // Shortest string "["
      new Table(93, 1, 54, new sbyte[] {37}),
/* NxS[  33] */ new Table(0, 0, -1, null), // Shortest string "^"
/* NxS[  34] */ new Table(0, 0, -1, null), // Shortest string "`"
/* NxS[  35] */ new Table(0, 0, -1, null), // Shortest string "|"
/* NxS[  36] */ new Table(0, 0, -1, null), // Shortest string "~"
/* NxS[  37] */ new Table(0, 0, -1, null), // Shortest string "[]"
/* NxS[  38] */ new Table(0, 0, -1, null), // Shortest string "LN"
/* NxS[  39] */ new Table(0, 0, -1, null), // Shortest string "PI"
/* NxS[  40] */ new Table(0, 0, -1, null), // Shortest string ">>"
/* NxS[  41] */ new Table(0, 0, -1, null), // Shortest string "<<"
/* NxS[  42] */ new Table(0, 0, -1, null), // Shortest string ":LN"
/* NxS[  43] */ // Shortest string ",E"
      new Table(43, 63, -1, new sbyte[] {124, -1, 124, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, 45}),
/* NxS[  44] */ // Shortest string ",G"
      new Table(105, 1, -1, new sbyte[] {45}),
/* NxS[  45] */ new Table(0, 0, -1, null), // Shortest string ",Q"
/* NxS[  46] */ // Shortest string ",d"
      new Table(97, 1, -1, new sbyte[] {45}),
/* NxS[  47] */ // Shortest string ",E+0"
      new Table(48, 10, -1, new sbyte[] {47, 47, 47, 47, 47, 47, 
          47, 47, 47, 47}),
/* NxS[  48] */ // Shortest string "0X0"
      new Table(48, 55, -1, new sbyte[] {48, 48, 48, 48, 48, 48, 
          48, 48, 48, 48, -1, -1, -1, -1, -1, -1, -1, 48, 48, 48, 48, 48, 
          48, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 48, -1, 48, 48, 48, 48, 48, 
          48}),
/* NxS[  49] */ // Shortest string "0B0"
      new Table(48, 48, -1, new sbyte[] {49, 49, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 49}),
/* NxS[  50] */ // Shortest string ",.0"
      new Table(48, 75, -1, new sbyte[] {50, 50, 50, 50, 50, 50, 
          50, 50, 50, 50, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 43, 
          -1, 44, -1, -1, -1, 44, -1, 44, -1, -1, 44, 45, 45, -1, 44, -1, 
          -1, -1, -1, 44, 44, -1, -1, -1, -1, -1, -1, 45, -1, 45, 46, 123, 
          45, -1, 45, -1, -1, 45, -1, 45, 45, -1, 45, 45, 45, -1, -1, 45, 
          -1, -1, -1, 45, 45}),
/* NxS[  51] */ new Table(0, 0, -1, null), // Shortest string "//"
/* NxS[  52] */ // Shortest string "#0"
      new Table(48, 75, -1, new sbyte[] {52, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, -1, -1, -1, -1, -1, -1, -1, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52, -1, -1, -1, -1, 52, -1, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
          52, 52, 52, 52, 52}),
/* NxS[  53] */ // Shortest string ""
      new Table(9, 118, 1, new sbyte[] {2, -1, 1, 1, 1, 1, 
          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
          1, 2, 3, 1, 4, 1, 5, 6, 1, 7, 8, 9, 10, 11, 12, 1, 
          13, 14, 11, 11, 11, 11, 11, 11, 11, 11, 11, 15, 16, 17, 18, 19, 
          1, 1, 20, 1, 21, 1, 22, 1, 1, 1, 23, 1, 1, 24, 25, 26, 
          27, 28, 1, 1, 29, 30, 1, 1, 1, 31, 1, 1, 32, 1, 1, 33, 
          1, 34, 20, 1, 21, 1, 22, 1, 1, 1, 23, 1, 1, 24, 25, 26, 
          27, 28, 1, 1, 29, 30, 1, 1, 1, 31, 1, 1, 1, 35, 1, 36}),
/* NxS[  54] */ // Shortest string "[\x01"
      new Table(93, 1, 54, new sbyte[] {37}),
/* NxS[  55] */ // Shortest string "XO"
      new Table(82, 33, -1, new sbyte[] {34, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 34}),
/* NxS[  56] */ // Shortest string "SI"
      new Table(78, 33, -1, new sbyte[] {38, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38}),
/* NxS[  57] */ // Shortest string "SQ"
      new Table(82, 33, -1, new sbyte[] {58, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 58}),
/* NxS[  58] */ // Shortest string "SQR"
      new Table(84, 33, -1, new sbyte[] {38, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38}),
/* NxS[  59] */ // Shortest string "NO"
      new Table(84, 33, -1, new sbyte[] {36, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 36}),
/* NxS[  60] */ // Shortest string "MO"
      new Table(68, 33, -1, new sbyte[] {5, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5}),
/* NxS[  61] */ // Shortest string "LO"
      new Table(71, 33, -1, new sbyte[] {38, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38}),
/* NxS[  62] */ // Shortest string "IN"
      new Table(84, 35, -1, new sbyte[] {38, -1, 38, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38, -1, 38}),
/* NxS[  63] */ // Shortest string "EX"
      new Table(80, 33, -1, new sbyte[] {38, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38}),
/* NxS[  64] */ // Shortest string "AB"
      new Table(83, 33, -1, new sbyte[] {38, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 38}),
/* NxS[  65] */ // Shortest string "AN"
      new Table(68, 33, -1, new sbyte[] {6, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 6}),
/* NxS[  66] */ // Shortest string "An"
      new Table(68, 48, -1, new sbyte[] {6, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 6, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 67}),
/* NxS[  67] */ // Shortest string "Ans"
      new Table(119, 1, -1, new sbyte[] {68}),
/* NxS[  68] */ // Shortest string "Answ"
      new Table(101, 1, -1, new sbyte[] {69}),
/* NxS[  69] */ // Shortest string "Answe"
      new Table(114, 1, -1, new sbyte[] {70}),
/* NxS[  70] */ // Shortest string "Answer"
      new Table(32, 1, -1, new sbyte[] {71}),
/* NxS[  71] */ // Shortest string "Answer\x20"
      new Table(116, 1, -1, new sbyte[] {72}),
/* NxS[  72] */ // Shortest string "Answer\x20t"
      new Table(111, 1, -1, new sbyte[] {73}),
/* NxS[  73] */ // Shortest string "Answer\x20to"
      new Table(32, 1, -1, new sbyte[] {74}),
/* NxS[  74] */ // Shortest string "Answer\x20to\x20"
      new Table(76, 33, -1, new sbyte[] {75, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 75}),
/* NxS[  75] */ // Shortest string "Answer\x20to\x20L"
      new Table(105, 1, -1, new sbyte[] {76}),
/* NxS[  76] */ // Shortest string "Answer\x20to\x20Li"
      new Table(102, 1, -1, new sbyte[] {77}),
/* NxS[  77] */ // Shortest string "Answer\x20to\x20Lif"
      new Table(101, 1, -1, new sbyte[] {78}),
/* NxS[  78] */ // Shortest string "Answer\x20to\x20Life"
      new Table(32, 1, -1, new sbyte[] {79}),
/* NxS[  79] */ // Shortest string "Answer\x20to\x20Life\x20"
      new Table(116, 1, -1, new sbyte[] {80}),
/* NxS[  80] */ // Shortest string "Answer\x20to\x20Life\x20t"
      new Table(104, 1, -1, new sbyte[] {81}),
/* NxS[  81] */ // Shortest string "Answer\x20to\x20Life\x20th"
      new Table(101, 1, -1, new sbyte[] {82}),
/* NxS[  82] */ // Shortest string "Answer\x20to\x20Life\x20the"
      new Table(32, 1, -1, new sbyte[] {83}),
/* NxS[  83] */ // Shortest string "Answer\x20to\x20Life\x20the\x20"
      new Table(85, 33, -1, new sbyte[] {84, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 84}),
/* NxS[  84] */ // Shortest string "Answer\x20to\x20Life\x20the\x20U"
      new Table(110, 1, -1, new sbyte[] {85}),
/* NxS[  85] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Un"
      new Table(105, 1, -1, new sbyte[] {86}),
/* NxS[  86] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Uni"
      new Table(118, 1, -1, new sbyte[] {87}),
/* NxS[  87] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Univ"
      new Table(101, 1, -1, new sbyte[] {88}),
/* NxS[  88] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Unive"
      new Table(114, 1, -1, new sbyte[] {89}),
/* NxS[  89] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Univer"
      new Table(115, 1, -1, new sbyte[] {90}),
/* NxS[  90] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Univers"
      new Table(101, 1, -1, new sbyte[] {91}),
/* NxS[  91] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe"
      new Table(32, 1, -1, new sbyte[] {92}),
/* NxS[  92] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20"
      new Table(97, 1, -1, new sbyte[] {93}),
/* NxS[  93] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20a"
      new Table(110, 1, -1, new sbyte[] {94}),
/* NxS[  94] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20an"
      new Table(100, 1, -1, new sbyte[] {95}),
/* NxS[  95] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and"
      new Table(32, 1, -1, new sbyte[] {96}),
/* NxS[  96] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20"
      new Table(69, 33, -1, new sbyte[] {97, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 97}),
/* NxS[  97] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20E"
      new Table(118, 1, -1, new sbyte[] {98}),
/* NxS[  98] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Ev"
      new Table(101, 1, -1, new sbyte[] {99}),
/* NxS[  99] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Eve"
      new Table(114, 1, -1, new sbyte[] {100}),
/* NxS[ 100] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Ever"
      new Table(121, 1, -1, new sbyte[] {101}),
/* NxS[ 101] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Every"
      new Table(116, 1, -1, new sbyte[] {102}),
/* NxS[ 102] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Everyt"
      new Table(104, 1, -1, new sbyte[] {103}),
/* NxS[ 103] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Everyth"
      new Table(105, 1, -1, new sbyte[] {104}),
/* NxS[ 104] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Everythi"
      new Table(110, 1, -1, new sbyte[] {105}),
/* NxS[ 105] */ // Shortest string "Answer\x20to\x20Life\x20the\x20Universe\x20and\x20Everythin"
      new Table(103, 1, -1, new sbyte[] {39}),
/* NxS[ 106] */ // Shortest string ":A"
      new Table(66, 33, -1, new sbyte[] {119, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 119}),
/* NxS[ 107] */ // Shortest string ":C"
      new Table(79, 33, -1, new sbyte[] {119, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 119}),
/* NxS[ 108] */ // Shortest string ":E"
      new Table(88, 33, -1, new sbyte[] {118, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 118}),
/* NxS[ 109] */ // Shortest string ":I"
      new Table(78, 33, -1, new sbyte[] {117, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 117}),
/* NxS[ 110] */ // Shortest string ":L"
      new Table(78, 34, -1, new sbyte[] {42, 116, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42, 116}),
/* NxS[ 111] */ // Shortest string ":S"
      new Table(73, 41, -1, new sbyte[] {113, -1, -1, -1, -1, -1, 
          -1, -1, 114, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 113, -1, -1, -1, -1, -1, 
          -1, -1, 114}),
/* NxS[ 112] */ // Shortest string ":T"
      new Table(65, 33, -1, new sbyte[] {113, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 113}),
/* NxS[ 113] */ // Shortest string ":SI"
      new Table(78, 33, -1, new sbyte[] {42, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42}),
/* NxS[ 114] */ // Shortest string ":SQ"
      new Table(82, 33, -1, new sbyte[] {115, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 115}),
/* NxS[ 115] */ // Shortest string ":SQR"
      new Table(84, 33, -1, new sbyte[] {42, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42}),
/* NxS[ 116] */ // Shortest string ":LO"
      new Table(71, 33, -1, new sbyte[] {42, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42}),
/* NxS[ 117] */ // Shortest string ":IN"
      new Table(84, 35, -1, new sbyte[] {42, -1, 42, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42, -1, 42}),
/* NxS[ 118] */ // Shortest string ":EX"
      new Table(80, 33, -1, new sbyte[] {42, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42}),
/* NxS[ 119] */ // Shortest string ":AB"
      new Table(83, 33, -1, new sbyte[] {42, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42}),
/* NxS[ 120] */ // Shortest string ",."
      new Table(48, 10, -1, new sbyte[] {50, 50, 50, 50, 50, 50, 
          50, 50, 50, 50}),
/* NxS[ 121] */ // Shortest string "0B"
      new Table(48, 48, -1, new sbyte[] {49, 49, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 49}),
/* NxS[ 122] */ // Shortest string "0X"
      new Table(48, 55, -1, new sbyte[] {48, 48, 48, 48, 48, 48, 
          48, 48, 48, 48, -1, -1, -1, -1, -1, -1, -1, 48, 48, 48, 48, 48, 
          48, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 48, -1, 48, 48, 48, 48, 48, 
          48}),
/* NxS[ 123] */ // Shortest string ",e"
      new Table(43, 3, -1, new sbyte[] {124, -1, 124}),
/* NxS[ 124] */ // Shortest string ",E+"
      new Table(48, 10, -1, new sbyte[] {47, 47, 47, 47, 47, 47, 
          47, 47, 47, 47}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = (byte)(code - NxS[state].min);
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal ParserScanner(Stream file) {
            SetSource(file); // no unicode option
        }   
#endif // !NOFILES

     internal ParserScanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{Unexpected}',	Shortest string "\x01"
        case 4: // Recognized '{Unexpected}',	Shortest string "#"
        case 15: // Recognized '{Unexpected}',	Shortest string ":"
        case 17: // Recognized '{Unexpected}',	Shortest string "<"
        case 19: // Recognized '{Unexpected}',	Shortest string ">"
        case 20: // Recognized '{Unexpected}',	Shortest string "A"
        case 22: // Recognized '{Unexpected}',	Shortest string "E"
        case 23: // Recognized '{Unexpected}',	Shortest string "I"
        case 24: // Recognized '{Unexpected}',	Shortest string "L"
        case 25: // Recognized '{Unexpected}',	Shortest string "M"
        case 26: // Recognized '{Unexpected}',	Shortest string "N"
        case 27: // Recognized '{Unexpected}',	Shortest string "O"
        case 29: // Recognized '{Unexpected}',	Shortest string "S"
        case 30: // Recognized '{Unexpected}',	Shortest string "T"
        case 31: // Recognized '{Unexpected}',	Shortest string "X"
        case 32: // Recognized '{Unexpected}',	Shortest string "["
/* Console.WriteLine( "LEX: Unexpected" ); */ SetName(); return (int)Token.ERROR;
            break;
        case 2: // Recognized '{Space}+',	Shortest string "\t"
/* skip */
            break;
        case 3: // Recognized '{OpFactorial}',	Shortest string "!"
/* Console.WriteLine( "LEX: OpFactorial" );*/            return (int)Token.OP_FACTORIAL;
            break;
        case 5: // Recognized '{OpMod}',	Shortest string "%"
/* Console.WriteLine( "LEX: OpMod" );      */            return (int)Token.OP_MOD;
            break;
        case 6: // Recognized '{OpAnd}',	Shortest string "&"
/* Console.WriteLine( "LEX: OpAnd" );      */            return (int)Token.OP_AND;
            break;
        case 7: // Recognized '{POpen}',	Shortest string "("
/* Console.WriteLine( "LEX: POpen" );      */            return (int)Token.P_OPEN;
            break;
        case 8: // Recognized '{PClose}',	Shortest string ")"
/* Console.WriteLine( "LEX: PClose" );     */            return (int)Token.P_CLOSE;
            break;
        case 9: // Recognized '{OpMult}',	Shortest string "*"
/* Console.WriteLine( "LEX: OpMult" );     */            return (int)Token.OP_MULT;
            break;
        case 10: // Recognized '{OpPlus}',	Shortest string "+"
/* Console.WriteLine( "LEX: OpPlus" );     */            return (int)Token.OP_PLUS;
            break;
        case 11: // Recognized '{Number}',	Shortest string ","
        case 14: // Recognized '{Number}',	Shortest string "0"
        case 43: // Recognized '{Number}',	Shortest string ",E"
        case 44: // Recognized '{Number}',	Shortest string ",G"
        case 45: // Recognized '{Number}',	Shortest string ",Q"
        case 46: // Recognized '{Number}',	Shortest string ",d"
        case 47: // Recognized '{Number}',	Shortest string ",E+0"
        case 50: // Recognized '{Number}',	Shortest string ",.0"
/* Console.WriteLine( "LEX: Number" );     */ GetNumber();    return (int)Token.NUMBER;
            break;
        case 12: // Recognized '{OpMinus}',	Shortest string "-"
/* Console.WriteLine( "LEX: OpMinus" );    */            return (int)Token.OP_MINUS;
            break;
        case 13: // Recognized '{OpDiv}',	Shortest string "/"
/* Console.WriteLine( "LEX: OpDiv" );      */            return (int)Token.OP_DIV;
            break;
        case 16: // Recognized '{OpSeparator}',	Shortest string ";"
/* Console.WriteLine( "LEX: OpSeparator"); */            return (int)Token.OP_SEPARATOR;
            break;
        case 18: // Recognized '{OpLet}',	Shortest string "="
/* Console.WriteLine( "LEX: OpLet" );      */            return (int)Token.OP_LET;
            break;
        case 21: // Recognized '{OpCombination}',	Shortest string "C"
/* Console.WriteLine( "LEX: OpCombination" ); */         return (int)Token.OP_COMBINATION;
            break;
        case 28: // Recognized '{OpPermutation}',	Shortest string "P"
/* Console.WriteLine( "LEX: OpPermutation" ); */         return (int)Token.OP_PERMUTATION;
            break;
        case 33: // Recognized '{OpPow}',	Shortest string "^"
/* Console.WriteLine( "LEX: OpPow" );      */            return (int)Token.OP_POW;
            break;
        case 34: // Recognized '{OpXor}',	Shortest string "`"
/* Console.WriteLine( "LEX: OpXor" );      */            return (int)Token.OP_XOR;
            break;
        case 35: // Recognized '{OpOr}',	Shortest string "|"
/* Console.WriteLine( "LEX: OpOr" );       */            return (int)Token.OP_OR;
            break;
        case 36: // Recognized '{OpNot}',	Shortest string "~"
/* Console.WriteLine( "LEX: OpNot" );      */            return (int)Token.OP_NOT;
            break;
        case 37: // Recognized '{Comment}',	Shortest string "[]"
/* skip */
            break;
        case 38: // Recognized '{OpFunction}',	Shortest string "LN"
/* Console.WriteLine( "LEX: OpFunction" ); */ SetName(); return (int)Token.OP_MATH_FUNC;
            break;
        case 39: // Recognized '{Const}',	Shortest string "PI"
/* Console.WriteLine( "LEX: Const" );      */ SetName();      return (int)Token.CONST;
            break;
        case 40: // Recognized '{OpRShift}',	Shortest string ">>"
/* Console.WriteLine( "LEX: OpRShift" );   */            return (int)Token.OP_RSHIFT;
            break;
        case 41: // Recognized '{OpLShift}',	Shortest string "<<"
/* Console.WriteLine( "LEX: OpLShift" );   */            return (int)Token.OP_LSHIFT;
            break;
        case 42: // Recognized '{OpFunction2}',	Shortest string ":LN"
/* Console.WriteLine( "LEX: OpFunction2"); */ SetName(); return (int)Token.OP_MATH_FUNC2;
            break;
        case 48: // Recognized '{HexNumber}',	Shortest string "0X0"
/* Console.WriteLine( "LEX: HexNumber" );  */ GetHexNumber(); return (int)Token.NUMBER;
            break;
        case 49: // Recognized '{BinNumber}',	Shortest string "0B0"
/* Console.WriteLine( "LEX: BinNumber" );  */ GetBinNumber(); return (int)Token.NUMBER;
            break;
        case 51: // Recognized '{OpDivInt}',	Shortest string "//"
/* Console.WriteLine( "LEX: OpDivInt" );   */            return (int)Token.OP_DIV_INT;
            break;
        case 52: // Recognized '{Variable}',	Shortest string "#0"
/* Console.WriteLine( "LEX: Variable" );   */ SetName();      return (int)Token.VARIABLE;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner


} // end namespace
